### ISSUE TITLE
(-2) Implement Organization model, schema and queries

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/openbeta-graphql#248]

**Comment by dww3000** [comment]
Impact: 0
Complex: 2

Task: -2

**Comment by zichongkao** [comment]
This has been implemented and merge in to the `develop` branch here: https://github.com/OpenBeta/openbeta-graphql/pull/254

There are still some leftover tasks that I will add to this tracker. 

I've renamed this task to "Implement .." instead of "Scaffold .." since the original plans firmed up and became the actual implementation. The Impact score of 0 is likely inaccurate since this is the actual deliverable of the LCO project. Complexity of 2 seems low for a 1.2K LoC PR as well.
