### ISSUE TITLE
Create Standardized Grade System

### ISSUE THREAD

**Issue by gibboj** [OpenBeta/openbeta-graphql#34]
Right now there is a lot of grades with different formats 
ex. V2/3, V2-3, V2+

* We should find one way to represent these grades, and update them in the data base.  Then only allow grades that fit the new format. 
* We should also think about how we can allow switching between grade systems.

**Comment by pau1phi11ips** [comment]
![bouldering grades](https://user-images.githubusercontent.com/677264/150114254-43381444-02ab-4067-a920-758a6a090161.jpg)

We attribute a score to each grade on UKC

**Comment by gibboj** [comment]
I think a score is a good way to represent the grade, the questions I'm not really sure about: 

1. Do we want to preserve the original grade, or at least original grade system? Or should we just save the score? 
2. Do we want to align the score system between bouldering & routes? Or let the frontend handle this? Ex. Boulders are scores 1-100 and Route grades are 101-200, vs all grades are between 1-100 & we align like equivalent grades ex: V3 === 5.10d === 15 
3. What do mixed / ice / trad grades look like, do we even I've seen grades listed as "Easy 4th" in the data, I'm not really sure what that means.  
4. [British Trad Grades](https://rockfax.com/climbing-guides/grades/)... I know very little about trad grading, if we want to use safety to represent this in total, and have grade just be the "technical" component

**Comment by pau1phi11ips** [comment]
Handling the grades is a bit of a nightmare tbh.

We have grade types and grade systems within each type. (UKC has 13 types and 26 systems) eg. 
- Bouldering
     - Fontainebleau
     - V grade
- Trad
     - British
     - French
     - Nordic
     - USA
- Sport
     - French
     - Nordic
     - USA
- Winter
    - Scottish
- Mixed
    - D grades
    - M grades
- Alpine

**Comment by vnugent** [comment]
can we store grade in its "native" unit per local custom?  

we should precalculate score to simplify querying and sorting.

USA 
```
# a sport or trad climb
grade: {
   value: "5.8",
   unit: "yds",
   score: <some number>
}

# bouldering
grade: {
  value: "2",
  unit: "V",
  score: < some number>
}

```

Most of Europe
```
# a sport or trad climb
grade: {
   value: "6a",
   unit: "fr",
   score: <some number>
}

# bouldering Fontainebleau
grade: {
   value: "6a",
   unit: "ft",
   score: <some number>
}
```

> Do we want to align the score system between bouldering & routes? Or let the frontend handle this? Ex. Boulders are scores 1-100 and Route grades are 101-200, vs all grades are between 1-100 & we align like equivalent grades ex: V3 === 5.10d === 15

it would be a nice-to-have. If there's a strong demand for aligning grades between routes and bouldering, we can always go back and update the database.

**Comment by vnugent** [comment]
For grades that aren't met our new format, I think we can
1. do our best guess and convert them to new format 
2.  flag those climbs in a "need-review" bucket for us human to look at later.  We can create a new Mongo collection to track them instead of polluting the climb and area schemas.

in between grades:
- 5.10a-b --> either 5.10a or 5.10b
- V3-4 --> V3+

Scrambling/approach grades:
- Easy 3rd --> 3.0
- Easy 4th --> 4.0
- Easy 5th --> 5.0

references:
- https://en.wikipedia.org/wiki/Yosemite_Decimal_System
- https://www.sierraclub.org/angeles/sierra-peaks/ratings-for-scramblers

**Comment by vnugent** [comment]
FYI we started a new climbing grades lib and also publish it on NPM https://github.com/OpenBeta/sandbag

@all-contributors please add @pau1phi11ips  for ideas

**Comment by musoke** [comment]
> Do we want to preserve the original grade, or at least original grade system? Or should we just save the score?

I'm sure that the score system will need lots of fine tuning as OpenBeta evolves.  Saving the original grade would allow the score system to be updated without losing data.  Perhaps a future score system would even to learn grade conversions from users as they contribute grades and tick climbs (see for example https://arxiv.org/abs/2111.08140 and https://arxiv.org/abs/2111.08140).  


I would propose that grades should be mapped to score ranges rather than individual scores.
For example, conversion of V-grades might look like

    V3-   --> [30, 32]
    V3    --> [30, 35]
    V3+   --> [33, 35]
    V4-   --> [35, 37]
    V4    --> [35, 40]


This would allow for grade to score conversion to be invertible, even in cases like  @vnugent's above:

> in between grades:
>
>    5.10a-b --> either 5.10a or 5.10b
>    V3-4 --> V3+

could instead be represented as subsets of the range of scores that represent 5.10a and 5.10b or V3 and V4. Perhaps V3-4 would map to 33 to 37 in the speculative scores above. This would preserve the grader's likely intention of representing a grade between those in YDS or the V-scale.

More importantly, score ranges accounts for differences in the widths and alignments of grades in different systems.  For example, according to [wikipedia](https://en.wikipedia.org/wiki/Grade_(climbing)), the 3 YDS grades 5.11a, 5.11b, and 5.11c correspond to two French grades 6c and 6c+, and one UIAA grade VIII-.  If this table is taken to be accurate, a conversion system that uses ranges would be able to convert UIAA VIII- to YDS 5.11a-5.11c and YDS 5.11a-5.11b to French 6c.

**Comment by vnugent** [comment]
@musoke we have since moved grade related code to [openbeta/sandbag](https://github.com/OpenBeta/sandbag).

> I would propose that grades should be mapped to score ranges rather than individual scores

The current implementation created by @gibboj does use [score ranges](https://github.com/OpenBeta/sandbag/blob/develop/src/data/boulder.csv) to handle overlaps between French and USA for both bouldering and route climb.

Currently the openbeta.io UI rejects user inputs that don't conform to the respective format rules (fairly relaxed I think).

Closing this.  Feel free to open new issues in  [openbeta/sandbag](https://github.com/OpenBeta/sandbag).
